# Generated by Django 3.1.7 on 2021-03-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_files', '0002_post_title_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='<django.db.models.fields.CharField>', max_length=255),
        ),
    ]
