# Generated by Django 3.1.7 on 2021-03-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_files', '0004_auto_20210303_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Title for webpage tab', max_length=255),
        ),
    ]
