# Generated by Django 3.1.7 on 2021-03-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_files', '0009_auto_20210303_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippit',
            field=models.CharField(default='Click above to see the blog post (created before snippit was added)', max_length=255),
        ),
    ]
